In [1]:
import pandas as pd

In [10]:
df = pd.read_csv('/content/final_data (2).csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29780 entries, 0 to 29779
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    29780 non-null  int64
 1   link          29780 non-null  object
 2   title         29717 non-null  object
 3   estate_type   29780 non-null  object
 4   province      29780 non-null  object
 5   district      29780 non-null  object
 6   ward          29780 non-null  object
 7   price         29780 non-null  float64
 8   square        29780 non-null  float64
 9   post_date     29780 non-null  object
 10  describe      29780 non-null  object
 11  numb_bedroom  23898 non-null  float64
 12  numb_toilet   21577 non-null  float64
 13  numb_floor    24675 non-null  float64
 14  price/square  29780 non-null  float64
dtypes: float64(6), int64(1), object(8)
memory usage: 3.4+ MB

In [11]:
df = df[df['price'] != 0]

In [12]:
print(len(df))
list_data = df.to_dict('records')

29065

In [13]:
df_final_data = pd.DataFrame(list_data)
df_final_data.to_csv('databds.csv')

In [14]:
print(len(df_final_data))
df_final_data.describe()

29065

,Unnamed: 0,price,square,numb_bedroom,numb_toilet,numb_floor,price/square
count,29065.000000,2.906500e+04,29065.000000,23415.000000,2.115800e+04,24183.000000,2.906500e+04
mean,14897.791949,7.481645e+15,152.097769,4.843092,1.789290e+04,5.265021,2.062355e+14
std,8599.766388,4.217733e+17,5278.452490,4.876713,2.601971e+06,3.544211,1.409182e+16
min,0.000000,1.000000e+06,1.000000,1.000000,1.000000e+00,1.000000,8.333300e+02
25%,7456.000000,3.900000e+09,40.000000,3.000000,3.000000e+00,4.000000,8.888889e+07
50%,14905.000000,6.000000e+09,52.000000,4.000000,4.000000e+00,5.000000,1.259259e+08
75%,22370.000000,1.220000e+10,78.000000,5.000000,5.000000e+00,5.000000,1.900000e+08
max,29779.000000,4.800000e+19,524300.000000,100.000000,3.784773e+08,60.000000,2.000000e+18

In [15]:
df_final_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29065 entries, 0 to 29064
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    29065 non-null  int64
 1   link          29065 non-null  object
 2   title         29003 non-null  object
 3   estate_type   29065 non-null  object
 4   province      29065 non-null  object
 5   district      29065 non-null  object
 6   ward          29065 non-null  object
 7   price         29065 non-null  float64
 8   square        29065 non-null  float64
 9   post_date     29065 non-null  object
 10  describe      29065 non-null  object
 11  numb_bedroom  23415 non-null  float64
 12  numb_toilet   21158 non-null  float64
 13  numb_floor    24183 non-null  float64
 14  price/square  29065 non-null  float64
dtypes: float64(6), int64(1), object(8)
memory usage: 3.3+ MB